@startuml

object "<u>nima: Instructor</u>" as instructor
object "<u>cleanCode: Textbook</u>" as textbook
object "<u>oneInstructorCourse: Course</u>" as course

course  o--  instructor
course  o--  textbook

object  instructor{
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object textbook {
    title = "Clean Code: A Handbook of Agile Software Craftsmanship"
    author = "Robert Cecil Martin"
    publisher = "Pearson"
}

object course {
    courseName = "CS5800 - Advanced Software Engineering"
    instructors = [nima]
    textbooks = [cleanCode]
}

@enduml
