@startuml

object "<u>demo1: Folder</u>" as demo1
object "<u>Source Files: Folder</u>" as source
object "<u>Include Path: Folder</u>" as include_path
object "<u>Remote Files: Folder</u>" as remote_files
object "<u>.phalcon: Folder</u>" as phalcon
object "<u>.cache: Folder</u>" as cache
object "<u>public: Folder</u>" as public
object "<u>.htaccess: File</u>" as htaccess
object "<u>.htrouter.php: File</u>" as htrouter
object "<u>index.html: File</u>" as index

demo1 *-- source
demo1 *-- include_path
demo1 *-- remote_files
source *-- phalcon
source *-- cache
source *-- public
public *-- htaccess
public *-- htrouter
public *-- index

object demo1 {
    name = "demo1"
    subfolders = ["Source Files", "Include Path", "Remote Files"]
    files = []
}

object source {
    name = "Source Files"
    subfolders = [".phalcon", ".cache", "public"]
    files = []
}

object include_path {
    name = "Include Path"
    subfolders = []
    files = []
}

object remote_files {
    name = "Remote Files"
    subfolders = []
    files = []
}

object phalcon {
    name = ".phalcon"
    subfolders = []
    files = []
}

object cache {
    name = ".cache"
    subfolders = []
    files = []
}

object public {
    name = "public"
    subfolders = []
    files = [".htaccess", ".htrouter.php", "index.html"]
}

object htaccess {
    name = ".htaccess"
}

object htrouter {
    name = ".htrouter.php"
}

object index {
    name = "index.html"
}

@enduml
